package pro1p1_diegomartinez;

import java.util.Arrays;
import java.util.Random;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;

public class Recurcion extends javax.swing.JFrame {

    /**
     * Creates new form Recurcion
     */
    
    static Scanner read = new Scanner(System.in);
    static Random random = new Random();
    
    public Recurcion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("American Typewriter", 3, 24)); // NOI18N
        jLabel1.setText("Recursión");

        jButton1.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jButton1.setText("Convertidor de Binario");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jButton2.setText("Multiplicador de Matrices");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("American Typewriter", 0, 14)); // NOI18N
        jButton3.setText("Menu");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        dispose();
        Menu screen=new Menu();
        screen.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        dispose();
        Binario bin=new Binario();
        bin.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        int r1,c1,r2,c2;
        r1=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero de filas en Matriz: 1"));
        c1=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero de columnas en Matriz: 1"));
        r2=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero de filas en Matriz: 2"));
        c2=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero de columnas en Matriz: 2"));
        if(c1!=r2){
            JOptionPane.showMessageDialog(null, "Para la multiplicacion de matrices, \n"
            + "el numero de columnas de Matriz 1,\n"
            + "deben ser igual a las filas de Matriz 2.\n"
            + "Vuelva a intentar.");
        }//End if
        int [][] a1 = new int[r1][c1];
        int [][] a2 = new int[r2][c2];
        a1=fill(a1,0,0);
        a2=fill(a2,0,0);
        int [][] a3 = new int[r1][c2];
        String x = "";
        JOptionPane.showMessageDialog(null, "Matriz 1: \n"+print(a1,0,0,x)+"\n"
                            +"Matriz 2: \n"+print(a2,0,0,x)+"\n"
                            + "Producto: \n"+print(multiplicacion(a1,a2,a3,0,0),0,0,x));
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recurcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recurcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recurcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recurcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recurcion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
    
    public static int[][] fill(int [][] array, int row,int col){
        if (row>=0 && row<array.length && col>=0 && col<array[row].length){
            int x = random.nextInt(10);
            array[row][col]=x;
        }//End if
        if (row<0 || row>= array.length || col<0 || col>=array[row].length){
            return array;
        }//End if 2
        else{
            if(col == array[row].length-1){
                return fill (array,row+1,0);
            }//End if 3
            else{
                return fill (array,row,col+1);
            }//End Else 2
        }//End Else 1
    }//End Fill
    
    public static String print (int [][] array, int row, int col, String res){
        if (row>=0 && row<array.length && col>=0 && col<array[row].length){
            res += "[" + array[row][col] + "]" + " ";
            if(array[row].length-1 == col){
                res+="\n";
            }//End if 2
        }//End if 1
        if (row<0 || row>= array.length || col<0 || col>=array[row].length){
            return res;
        }//End if 3
        else{
            if(col == array[row].length-1){
                return print(array,row+1,0,res);
            }//End if 4
            else{
                return print(array,row,col+1,res);
            }//End Else 2
        }//End Else 1
    }//End Print

    public static int rowProduct (int [][] a1, int [][] a2, int i, int j, int k, int sum){
        if (k>=0 && k<a1[0].length){
            sum+=a1[i][k]*a2[k][j];
        }//End if
        if (k<0 || k>= a1[0].length || k>=a2.length){
            return sum;
        }//End if 2
        else{
            if(k == a1[0].length-1){
            }//End else 1
            else{
                return rowProduct (a1,a2,i,j,k+1,sum);
            }//End Else 2
        }//End Else 3
        return sum;
        /*
        Este programa va agarrando la k que es la multiplicadora de las
        columnas de a1 y las filas de a2 y lo va iternado agregando 1
        para ir sacando la suma y la va acumulando. Esta suma acumulada 
        sera devuelta a multiplicacion para ser agregada a a la matriz solucion (a3)
        */
    }//End rowProduct

    public static int [][] multiplicacion (int [][] a1, int [][] a2, int [][] a3, int i, int j){
        if (i>=0 && i<a3.length && j>=0 && j<a3[i].length){
            a3[i][j]=rowProduct(a1,a2,i,j,0,0);
        }//End if
        if (i<0 || i>= a3.length || j<0 || j>=a3[i].length){
            return a3;
        }//End if 2
        else{
            if(j == a3[i].length-1){
                return multiplicacion (a1,a2,a3,i+1,0);
            }//End if 3
            else{
                return multiplicacion (a1,a2,a3,i,j+1);
            }//End Else 2
        }//End Else 1
        /*Este programa lo que va haciendo es recorriendo uno por uno i y j y cada vez lo manda hacia
        el programa de row product para que alli con la tercera variable de k, esto sea multiplicado en forma
        de producto punto y la valiable sea agregada a a3.
        */
    }//End multiplicacion

}
